version: '3.9'

services:
  app:
    build: ./app
    container_name: web-app
    volumes:
      - ./app/src:/app
    ports:
      - 8501:8501

  api:
    build: ./api
    container_name: web-api
    volumes:
      - ./api:/app
    ports:
      - 4000:4000

  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - ./api/.env
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d:ro
    ports:
      - 3200:3306

