version: "3.9"

services:
  app-test:
    build: ./app
    container_name: web-app-test
    volumes:
      - ./app/src:/app
    ports:
      - 8502:8501

  api-test:
    build: ./api
    container_name: web-api-test
    volumes:
      - ./api:/app
    ports:
      - 4001:4000

  db-test:
    image: mysql:8.0
    container_name: mysql-db-test
    env_file:
      - ./api/.env
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d:ro
    ports:
      - 3201:3306
